function F = FfunctionEKF(dth1,dth2,th1,th2)
%FFUNCTIONEKF
%    F = FFUNCTIONEKF(DTH1,DTH2,TH1,TH2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    23-May-2015 10:55:59

t3 = th1-th2;
t2 = sin(t3);
t4 = t2.^2;
t5 = t4.*2.916e3;
t6 = t5+2.0527e4;
t7 = 1.0./t6;
t8 = th1.*2.0;
t13 = th2.*2.0;
t9 = t8-t13;
t10 = cos(t3);
t11 = dth2.^2;
t12 = dth1.^2;
t14 = sin(t9);
t15 = t10.*t11.*1.97e2;
t16 = cos(t9);
t17 = t12.*t16.*1.08e2;
t18 = t15+t17;
t19 = 1.0./t6.^2;
t20 = t2.*t11.*1.97e2;
t21 = t12.*t14.*5.4e1;
t22 = t20+t21;
t23 = t2.*t10.*t19.*t22.*1.57464e5;
t24 = t10.*t12.*1.19e2;
t25 = t11.*t16.*2.7e1;
t26 = t24+t25;
t27 = t7.*t26.*1.08e2;
t28 = t2.*t12.*1.19e2;
t29 = t11.*t14.*(2.7e1./2.0);
t30 = t28+t29;
F = reshape([dth1.*t7.*t14.*-2.916e3,dth1.*t2.*t7.*2.5704e4,1.0,0.0,dth2.*t2.*t7.*-1.0638e4,dth2.*t7.*t14.*2.916e3,0.0,1.0,t23-t7.*t18.*2.7e1,t27-t2.*t10.*t19.*t30.*6.29856e5,0.0,0.0,-t23+t7.*t18.*2.7e1,-t27+t2.*t10.*t19.*t30.*6.29856e5,0.0,0.0],[4, 4]);
