function G = GfunctionEKF
%GFUNCTIONEKF
%    G = GFUNCTIONEKF

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    13-Jun-2015 13:01:12

G = [0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0];
