function F = Ffunc(accX,accY,accZ,gyroY,gyroZ,ph,si,th)
%FFUNC
%    F = FFUNC(ACCX,ACCY,ACCZ,GYROY,GYROZ,PH,SI,TH)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    03-Jun-2015 17:23:16

t2 = conj(gyroZ);
t3 = cos(th);
t4 = sin(si);
t5 = conj(gyroY);
t6 = cos(si);
t7 = sin(th);
t8 = sin(ph);
t9 = cos(ph);
t10 = conj(accZ);
t11 = conj(accY);
t12 = conj(accX);
t13 = t4.*t9;
t14 = t13-t6.*t7.*t8;
t15 = t6.*t9;
t16 = t4.*t7.*t8;
t17 = t15+t16;
t18 = t6.*t8;
t19 = t18-t4.*t7.*t9;
t20 = t4.*t8;
t21 = t6.*t7.*t9;
t22 = t20+t21;
F = reshape([0.0,-t4.*t5-t2.*t3.*t6,t5.*t6-t2.*t3.*t4,t10.*t19+t11.*t22,-t11.*t14-t10.*t17,-t3.*t4.*t10+t3.*t6.*t11,0.0,0.0,0.0,t2.*t3,t2.*t4.*t7,-t2.*t6.*t7,-t7.*t9.*t12+t3.*t4.*t9.*t11+t3.*t6.*t9.*t10,-t7.*t8.*t12+t3.*t4.*t8.*t11+t3.*t6.*t8.*t10,-t3.*t12-t4.*t7.*t11-t6.*t7.*t10,0.0,0.0,0.0,0.0,0.0,0.0,t10.*t14-t11.*t17-t3.*t8.*t12,-t11.*t19+t10.*t22+t3.*t9.*t12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[9, 9]);
