function predict = predictFunc(accX,accY,accZ,g,gyroX,gyroY,gyroZ,ph,si,th,vx,vy,vz)
%PREDICTFUNC
%    PREDICT = PREDICTFUNC(ACCX,ACCY,ACCZ,G,GYROX,GYROY,GYROZ,PH,SI,TH,VX,VY,VZ)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    03-Jun-2015 17:23:21

t2 = conj(gyroZ);
t3 = conj(gyroY);
t4 = sin(si);
t5 = cos(si);
t6 = cos(th);
t7 = sin(th);
t8 = sin(ph);
t9 = cos(ph);
t10 = conj(accY);
t11 = conj(accZ);
t12 = conj(accX);
predict = [conj(gyroX)+t2.*t7,t3.*t5-t2.*t4.*t6,t3.*t4+t2.*t5.*t6,-t10.*(t5.*t8-t4.*t7.*t9)+t11.*(t4.*t8+t5.*t7.*t9)+t6.*t9.*t12,t10.*(t5.*t9+t4.*t7.*t8)-t11.*(t4.*t9-t5.*t7.*t8)+t6.*t8.*t12,-g-t7.*t12+t4.*t6.*t10+t5.*t6.*t11,vx,vy,vz];
