function Q = QfunctionFullEKF(Tp1,Tp2,Ty1,Ty2,dph3,dph4,dth3,dth4,ph3,ph4,signdph3,signdph4,signdth3,signdth4,th3,th4)
%QFUNCTIONFULLEKF
%    Q = QFUNCTIONFULLEKF(TP1,TP2,TY1,TY2,DPH3,DPH4,DTH3,DTH4,PH3,PH4,SIGNDPH3,SIGNDPH4,SIGNDTH3,SIGNDTH4,TH3,TH4)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    13-Jun-2015 12:56:50

t2 = cos(ph4);
t3 = sin(ph3);
t4 = sin(th3);
t5 = cos(ph3);
t6 = dph4.^2;
t7 = sin(ph4);
t8 = dth4.^2;
t9 = t2.^2;
t10 = sin(th4);
t11 = dph3.^2;
t12 = dth3.^2;
t13 = t5.^2;
t14 = cos(th3);
t15 = signdph4.*t2.*t6.*8.26875e-4;
t25 = signdth4.*t7.*t8.*t9.*t10.*8.26875e-4;
t16 = t15-t25;
t17 = signdph3.*t5.*t11.*1.42884e-3;
t18 = t17-signdth3.*t3.*t4.*t12.*t13.*1.42884e-3;
t19 = signdph4.*t6.*t7.*8.26875e-4;
t20 = signdth4.*t2.*t8.*t9.*t10.*8.26875e-4;
t21 = t19+t20;
t22 = signdph3.*t3.*t11.*1.42884e-3;
t23 = signdth3.*t4.*t5.*t12.*t13.*1.42884e-3;
t24 = t22+t23;
t26 = cos(th4);
Q = [0.0;0.0;0.0;0.0;0.0;0.0;Tp1+t3.*t4.*t16.*(9.0./2.5e1)+t3.*t4.*t18.*(2.7e1./1.0e2)-t4.*t5.*t21.*(9.0./2.5e1)-t4.*t5.*t24.*(2.7e1./1.0e2)-signdth3.*t12.*t13.*t14.^2.*3.857868e-4-signdth4.*t8.*t9.*t14.*t26.*2.97675e-4;Ty1-t5.*t14.*t16.*(9.0./2.5e1)-t5.*t14.*t18.*(2.7e1./1.0e2)-t3.*t14.*t21.*(9.0./2.5e1)-t3.*t14.*t24.*(2.7e1./1.0e2);Tp2-t2.*t10.*t21.*(9.0./4.0e1)+t7.*t10.*t16.*(9.0./4.0e1)-signdth4.*t8.*t9.*t26.^2.*1.86046875e-4;Ty2-t2.*t16.*t26.*(9.0./4.0e1)-t7.*t21.*t26.*(9.0./4.0e1)];
