function C = CfunctionEKF(dth1,dth2,th1,th2)
%CFUNCTIONEKF
%    C = CFUNCTIONEKF(DTH1,DTH2,TH1,TH2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    01-Jun-2015 10:08:49

t2 = th1-th2;
t3 = sin(t2);
C = reshape([0.0,dth1.*t3.*(-8.1e-3),dth2.*t3.*8.1e-3,0.0],[2, 2]);
