function M = MfunctionEKF(th1,th2)
%MFUNCTIONEKF
%    M = MFUNCTIONEKF(TH1,TH2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    01-Jun-2015 10:08:50

t2 = th1-th2;
t3 = cos(t2);
t4 = t3.*8.1e-3;
M = reshape([3.57e-2,t4,t4,1.4775e-2],[2, 2]);
