function update = updateFunctionFullEKF(ddph,ddth,dph,dth,ph,th)
%UPDATEFUNCTIONFULLEKF
%    UPDATE = UPDATEFUNCTIONFULLEKF(DDPH,DDTH,DPH,DTH,PH,TH)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    02-Jul-2015 12:38:37

t2 = sin(th);
t3 = cos(th);
t4 = cos(ph);
t5 = sin(ph);
t6 = dth.^2;
t7 = ddth.*t3.*(3.3e1./5.0e1);
t8 = t7-t2.*t6.*(3.3e1./5.0e1);
t9 = dph.*t3.*t4.*(3.3e1./5.0e1);
t10 = t9-dth.*t2.*t5.*(3.3e1./5.0e1);
t11 = dph.*t10;
t12 = dph.*t2.*t5.*(3.3e1./5.0e1);
t13 = t12-dth.*t3.*t4.*(3.3e1./5.0e1);
t14 = ddph.*t3.*t5.*(3.3e1./5.0e1);
t15 = ddth.*t2.*t4.*(3.3e1./5.0e1);
t16 = t11+t14+t15-dth.*t13;
t17 = dph.*t3.*t5.*(3.3e1./5.0e1);
t18 = dth.*t2.*t4.*(3.3e1./5.0e1);
t19 = t17+t18;
t20 = dph.*t19;
t21 = dph.*t2.*t4.*(3.3e1./5.0e1);
t22 = dth.*t3.*t5.*(3.3e1./5.0e1);
t23 = t21+t22;
t24 = dth.*t23;
t25 = ddth.*t2.*t5.*(3.3e1./5.0e1);
t26 = t20+t24+t25-ddph.*t3.*t4.*(3.3e1./5.0e1);
t27 = sqrt(2.0);
update = [t2.*(-4.9e1./5.0)+t2.*t8-t3.*t4.*t16-t3.*t5.*t26,t3.*(4.9e1./5.0)-t3.*t8-t2.*t4.*t16-t2.*t5.*t26,dth.*t4,dph,t3.*t4.*t27.*(1.0./2.0)+t3.*t5.*t27.*(1.0./2.0),t4.*t27.*(1.0./2.0)-t5.*t27.*(1.0./2.0),t2.*t4.*t27.*(1.0./2.0)+t2.*t5.*t27.*(1.0./2.0)];
