function update = updateFunctionFullEKF(ddth1,ddth2,dth1,dth2,th1,th2)
%UPDATEFUNCTIONFULLEKF
%    UPDATE = UPDATEFUNCTIONFULLEKF(DDTH1,DDTH2,DTH1,DTH2,TH1,TH2)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    23-May-2015 11:38:31

t2 = sin(th1);
t3 = cos(th1);
t4 = dth1.^2;
t5 = ddth1.*t3.*(9.0./2.5e1);
t13 = t2.*t4.*(9.0./2.5e1);
t6 = t5-t13;
t7 = ddth1.*t2.*(9.0./2.5e1);
t8 = t3.*t4.*(9.0./2.5e1);
t9 = t7+t8;
t10 = sqrt(2.0);
t11 = sin(th2);
t12 = cos(th2);
t14 = dth2.^2;
t15 = ddth2.*t12.*(3.0./1.0e1);
t16 = t5-t13+t15-t11.*t14.*(3.0./1.0e1);
t17 = ddth2.*t11.*(3.0./1.0e1);
t18 = t12.*t14.*(3.0./1.0e1);
t19 = t7+t8+t17+t18;
update = [t2.*(-4.9e1./5.0)+t2.*t6-t3.*t9,t3.*(4.9e1./5.0)-t3.*t6-t2.*t9,dth1,t3.*t10.*(1.0./2.0),t2.*t10.*(1.0./2.0),t11.*(-4.9e1./5.0)+t11.*t16-t12.*t19,t12.*(4.9e1./5.0)-t12.*t16-t11.*t19,dth2,t10.*t12.*(1.0./2.0),t10.*t11.*(1.0./2.0)];
