function update = updateFunctionEKF(ddth1,ddth2,ddth3,ddth4,dth1,dth2,dth3,dth4,th1,th2,th3,th4)
%UPDATEFUNCTIONEKF
%    UPDATE = UPDATEFUNCTIONEKF(DDTH1,DDTH2,DDTH3,DDTH4,DTH1,DTH2,DTH3,DTH4,TH1,TH2,TH3,TH4)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    14-Jun-2015 17:59:04

t2 = cos(th1);
t3 = sqrt(2.0);
t4 = sin(th1);
t5 = sin(th2);
t6 = cos(th2);
t7 = dth1.^2;
t8 = dth2.^2;
t9 = ddth1.*t2.*(1.0./2.0);
t10 = ddth2.*t6.*(3.0./1.0e1);
t19 = t4.*t7.*(1.0./2.0);
t20 = t5.*t8.*(3.0./1.0e1);
t11 = t9+t10-t19-t20;
t12 = ddth1.*t4.*(1.0./2.0);
t13 = ddth2.*t5.*(3.0./1.0e1);
t14 = t2.*t7.*(1.0./2.0);
t15 = t6.*t8.*(3.0./1.0e1);
t16 = t12+t13+t14+t15;
t17 = sin(th3);
t18 = cos(th3);
t21 = dth3.^2;
t22 = ddth3.*t18.*(9.0./2.5e1);
t29 = t17.*t21.*(9.0./2.5e1);
t23 = t9+t10-t19-t20+t22-t29;
t24 = ddth3.*t17.*(9.0./2.5e1);
t25 = t18.*t21.*(9.0./2.5e1);
t26 = t12+t13+t14+t15+t24+t25;
t27 = sin(th4);
t28 = cos(th4);
t30 = dth4.^2;
t31 = ddth4.*t28.*(3.0./1.0e1);
t32 = t9+t10-t19-t20+t22-t29+t31-t27.*t30.*(3.0./1.0e1);
t33 = ddth4.*t27.*(3.0./1.0e1);
t34 = t28.*t30.*(3.0./1.0e1);
t35 = t12+t13+t14+t15+t24+t25+t33+t34;
update = [t4.*(-4.9e1./5.0),t2.*(4.9e1./5.0),dth1,t2.*t3.*(1.0./2.0),t3.*t4.*(1.0./2.0),t5.*(-4.9e1./5.0)+t5.*t11-t6.*t16,t6.*(4.9e1./5.0)-t6.*t11-t5.*t16,dth2,t3.*t6.*(1.0./2.0),t3.*t5.*(1.0./2.0),t17.*(-4.9e1./5.0)+t17.*t23-t18.*t26,t18.*(4.9e1./5.0)-t18.*t23-t17.*t26,dth3,t3.*t18.*(1.0./2.0),t3.*t17.*(1.0./2.0),t27.*(-4.9e1./5.0)+t27.*t32-t28.*t35,t28.*(4.9e1./5.0)-t28.*t32-t27.*t35,dth4,t3.*t28.*(1.0./2.0),t3.*t27.*(1.0./2.0)];
