function F = FfunctionEKF(dph,dth,ph,th)
%FFUNCTIONEKF
%    F = FFUNCTIONEKF(DPH,DTH,PH,TH)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    02-Jul-2015 12:08:08

t2 = ph.*2.0;
t3 = sin(t2);
t4 = cos(t2);
t5 = t4.*7.6e2;
t6 = t5+1.849e3;
t7 = 1.0./t6;
t8 = th.*2.0;
t9 = dph.^2;
t10 = sin(t8);
t11 = sin(th);
t12 = t11.^2;
t13 = t12.*1.089e3;
t14 = t13-2.609e3;
t15 = 1.0./t14;
t16 = cos(t8);
t17 = dph.*t10.*1.089e3;
F = reshape([dph.*t3.*t7.*1.52e3,-t15.*(t17-dth.*t3.*7.6e2)+dth.*t3.*t15.*7.6e2,1.0,0.0,t7.*(dph.*t10.*2.178e3-dth.*t3.*3.04e3).*(-1.0./2.0),dth.*t10.*t15.*-1.089e3,0.0,1.0,t7.*t9.*t16.*-1.089e3,dph.*dth.*t15.*t16.*-2.178e3+dth.*t11.*1.0./t14.^2.*cos(th).*(t17-dth.*t3.*7.6e2).*2.178e3,0.0,0.0,t3.*1.0./t6.^2.*(t9.*t10.*1.089e3-dph.*dth.*t3.*3.04e3).*-7.6e2+dph.*dth.*t4.*t7.*3.04e3,dth.^2.*t4.*t15.*1.52e3,0.0,0.0],[4, 4]);
